repos:
  - repo: local
    hooks:
      - id: prevent-commit-to-main-or-production
        name: Prevent commit to main or production branches
        entry: bash scripts/prevent_commit_to_main_or_production.sh
        language: system
        stages: [pre-commit]